services:
  backend:
    image: adeife08/backend-server:v3
    container_name: backend-server
    env_file:
      - .env
    ports:
      - "5002:5002"
    environment:
      - PORT=5002

  client:
    image: adeife08/client-server:v3
    container_name: client-server
    depends_on: 
      - backend
    ports:
      - "5003:5003"
    environment:
#      - APP_API_URL=http://:8092
      - PORT=5003

  