name: Deploy Application 

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed
    

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
        id-token: write   # REQUIRED for OIDC
        contents: read

    env:
        AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
            aws-region: ${{env.AWS_REGION}}
            role-to-assume: arn:aws:iam::749929394992:role/gh-actions-role

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Get EC2 IP from Terraform state
        id: get_ip
        run: |
            cd aws-infra
            terraform init -input=false -no-color
            EC2_IP=$(terraform output -raw ec2_public_ip 2>/dev/null | head -n 1 | tr -d '\r')
            echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and Push Client Image
        run: |
            cd client
            docker build -t adeife08/client-server:v2 .
            docker push adeife08/client-server:v2

      - name: Build and Push Backend Image
        run: |
            cd backend
            docker build -t adeife08/backend-server:v2 .
            docker push adeife08/backend-server:v2

      - name: Set up SSH Key
        run: |
            mkdir -p ~/.ssh
            echo "${{secrets.DEMO_SSH_KEY}}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

      - name: Copy docker-compose.yml to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
            docker-compose.yml \
            ec2-user@98.92.183.183:/home/ec2-user \
#          echo "${{secrets.DEMO_SSH_KEY}}" > key.pem
 #         chmod 

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 98.92.183.183
          username: ec2-user
          key: ${{secrets.DEMO_SSH_KEY}}
          script: |
            echo "You've successfully connected to the instance"
            sudo yum update -y || true
#            sudo yum install -y git || true
            sudo amazon-linux-extras enable docker
            sudo yum install -y docker || true
            sudo systemctl start docker 
            sudo systemctl enable docker
            sudo usermod -aG docker ec2-user || true
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
              -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker --version
            docker-compose --version
            cd /home/ec2-user
#            git clone https://github.com/Adeife79/Blog-website.git || true
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker-compose down || true
            docker-compose pull
            docker-compose up -d 
            
            
